# Generated by Django 5.2.7 on 2025-11-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadeddocument',
            name='user',
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
