# Generated by Django 5.2.7 on 2025-11-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_email_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
